- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: Add the user with a bash shell, appending the group 'wheel' and 'docker' to the user's groups
  user:
    name: "{{ vars.hb_user }}"
    password: "{{ vars.hb_password | password_hash('sha512') }}"
    home: "/home/{{ vars.hb_user }}"
    shell: /bin/bash
    groups: wheel,docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
- name: Register dummy host with user variable
  add_host:
    name: "dummy"
    hb_user_map: "{{vars.hb_user}}"
- name: Register dummy host with passwd variable
  add_host:
    name: "dummy"
    hb_pass_map: "{{vars.hb_password}}"
- name: Set directory and permissions
  file:
    path: /var/local/healthbot
    state: directory
    owner: "{{ vars.hb_user }}"
    recurse: yes
    mode: 0775
- name: Add user to sudoers
  shell: sed -i -r -e '/^\s*Defaults\s+secure_path/ s[=(.*)[=\1:/usr/local/bin[' /etc/sudoers
- name: Set No Password access
  shell: sed -i -r -e '/NOPASSWD/s/# //' /etc/sudoers