- name: debug for hb filename
  debug:
    msg: "copying RPM {{ hb_rpm_patha }}/{{ hb_rpm_map.files[0].path | basename }}"
- name: Transfer HB rpm file
  copy:
    src: "{{ hb_rpm_path }}/{{ hb_rpm_map.files[0].path | basename }}"
    dest: "/home/"
  register: copied
- name: Install HB rpm
  yum:
    name: "/home/{{ hb_rpm_map.files[0].path | basename }}"
    state: present
- name: Check that certs folder isn't created
  stat:
    path: /var/local/healthbot/certs
  register: stat_result
- name: Set certificates folder
  shell: mkdir /var/local/healthbot/certs
  when: stat_result.stat.exists == False
- name: Gernerate certs files
  shell: openssl req -nodes -x509 -newkey rsa:4096 -keyout /var/local/healthbot/certs/key.pem -out /var/local/healthbot/certs/cert.pem -days 36525 -subj "/C=US/ST=Ca/L=Svl/O=Juniper Networks/OU=Org/CN=localhost"
- name: Set directory and permissions
  file:
    path: /var/local/healthbot
    state: directory
    owner: "{{ hb_user_map }}"
#- name: Set directory permissions
#  shell: chown "{{ hb_user_map }}" /var/local/healthbot
