- name: Setup Healthbot 
  shell: healthbot setup -c /var/local/healthbot/healthbot.conf
- name: Set directory and permissions
  file:
    path: /var/local/healthbot
    state: directory
    owner: "{{ hb_user_map }}"